### ISSUE TITLE
Same recs for me and my friends, not updates itself

### ISSUE THREAD

**Issue by Brissinger** [rickycorte/maki-web#17] opened 2022-06-09 11:42 UTC
Hi, i am using hacker09 script for your generator https://myanimelist.net/forum/?topicid=2016752
After 8 or more days i have the same recs, nothing has changed (one anime i completed is here - Ged Senki) and my friends have exactly the same recs as me.
![obraz](https://user-images.githubusercontent.com/72404411/172837723-44b481b4-d475-4ca3-8927-6a614bb49f79.png)
![obraz](https://user-images.githubusercontent.com/72404411/172837870-baa69fef-ef1e-48f8-9bf0-0b870e4e336d.png)
![obraz](https://user-images.githubusercontent.com/72404411/172838841-fb3c35be-ce0a-4a6a-a36f-78d0c0f7fde9.png)
![obraz](https://user-images.githubusercontent.com/72404411/172838979-1fbdc2be-ba95-4023-ae88-324b504f3ebd.png)

**Comment by rickycorte** [comment] 2022-06-09 12:29
I'm aware of this issue and I'm trying to fix it as soon as possible.

**Comment by rickycorte** [comment] 2022-06-10 08:48
The issue is now fixed.
The problem was caused by a crash during the daily model update that prevented Maki to actually use new user lists.

**Closed by rickycorte** 2022-06-10 08:48 UTC
